---
# Employee records
#~ martin:
    #~ name: Martin D'vloper
    #~ job: Developer
    #~ skills:
      #~ - python
      #~ - perl
      #~ - pascal
#~ tabitha:
    #~ name: Tabitha Bitumen
    #~ job: Developer
    #~ skills:
      #~ - lisp
      #~ - fortran
      #~ - erlang

mission_ids:
  - SCR
  - NFT
  - FY
  - SOY
  - BEANS

temperature_offset: 0.0
humidity_offset: 0.0